name: Node CI
on:
  pull_request:
    branches: [main, dev, dotnet]
    paths: ["node-package/**"]
  push:
    branches: [main, dev, dotnet]
    paths: ["node-package/**"]
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node-package
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - run: npm test --if-present
